### ISSUE TITLE
please set locale for multi-language,thank you

### ISSUE THREAD

**Issue by markqiu** [QuantumObject/docker-shiny#4]
# Set the locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

**Comment by angelrr7702** [comment]
please add the reason for that you needed it ,or what it suppose to fix ... 

it is ok if I added it at the startup script of the container ... I don't want to add 4 layer to the container for the 4 different command at Doker  file. I understand that ufs have some limitation of layer allowed , still i have a lot of them for this container but I want to keep minimal possible.

**Comment by angelrr7702** [comment]
Hi,
  done, update container.

**Comment by angelrr7702** [comment]
Hi,
 
 I have to fix the problem at the quantumobject/docker-baseimage. the new build now work fine. 

sincerely
Angel Rodriguez

**Comment by markqiu** [comment]
thank you very much.
