### ISSUE TITLE
Error: EACCES - Invalid application configuration.

### ISSUE THREAD

**Issue by xvrdm** [QuantumObject/docker-shiny#6]
I installed as explained and run with:

```
docker run -d -p 3838:3838 -v <LOCAL DIRECTORY PATH>:/srv/shiny-server quantumobject/docker-shiny
```

But I get an error message when I try to connect.

```
An error has occurred

Invalid application configuration.
EACCES, stat '/srv/shiny-server/shinyApp1'
```
![capture_shiny](https://cloud.githubusercontent.com/assets/3109069/18579506/57297e9c-7bf6-11e6-9f69-0e4973f0db43.JPG)

Reading the `/etc/shiny-server/shiny-server.conf` has the `run_as shiny` parameter, I tried to change the owner of my `ui.R` and `server.R` files to `shiny` but it did not fix the issue.

I tried to place `ui.R` and `server.R` both directly in `/srv/shiny-server/` and in a dedicated `shinyApp1` folder (changing the url accordingly). No success.

Thanks for providing this image.

**Comment by angelrr7702** [comment]
Hi,  

did you can check permission and ownership of folder from inside of shiny container and outside ?
 
did you can tell what linux or other OS you are using for running container ? 

sincerely
Angel Rodriguez

**Comment by xvrdm** [comment]
It's a Centos 7 VPS. 

I know changed the ownership of `/srv/shiny-server` to `shiny` and it works! Before I had only changed the ownership of my own dashboard folder `shinyApp1` and the files inside.

If this is required every time, it might be worth updating the documentation on docker hub.

Thanks for your help!

**Comment by angelrr7702** [comment]
valid point . I change the container to every time it restart or start to change ownership to  /srv/shiny-server to shiny.  if you add anything to the volume only need to restart the container to get it working. 

the build for it will happen later today .. still no available.

sincerely
Angel Rodriguez

**Comment by xvrdm** [comment]
Just tried it, works like a charm :+1:
