### ISSUE TITLE
#question: bash shell script clarification

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [QuantumObject/docker-shiny#7]
Hi Angel, 
I'm building a local image for a shiny app based on your Dockerfile, but I keep getting the error: 

```
gpg: requesting key E084DAB9 from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c (echo "deb http://cran.mtu.edu/bin/linux/ubuntu `cat /etc/container_environment/DISTRIB_CODENAME`/" >> /etc/apt/sources.list && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9)' returned a non-zero code: 2
```

What exactly the Dockerfile command 
`RUN (echo "deb http://cran.mtu.edu/bin/linux/ubuntu `cat /etc/container_environment/DISTRIB_CODENAME`/" >> /etc/apt/sources.list && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9)`
is computing?? 

Many thanks,
Alex

**Comment by angelrr7702** [comment]
'cat /etc/container_environment/DISTRIB_CODENAME ' is a variable for my container that return  Ubuntu name distribution ... there are other way to do it but will add more space to the container ... you need to replace the complete line between '.... ' for ubuntu name distribution (xenial, willy, etc)

I used to make sure it easier to change/upgrade  the ubuntu distribution for my container. 
 
in the case of xenial ubuntu the command will be : 

echo "deb http://cran.mtu.edu/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list 
&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9)'
