### ISSUE TITLE
Installing packages

### ISSUE THREAD

**Issue by vikjam** [QuantumObject/docker-shiny#8]
This is a bit of a shot in the dark to bug you about, but do you have any insight into why I'm facing errors while trying to install packages?

```
sudo su - -c "R -e \"install.packages('plyr', repos='https://cran.rstudio.com/')\""
```

Here's some of the output from the error.
```
* installing *source* package 'plyr' ...
** package 'plyr' successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
/usr/lib/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 4
ERROR: compilation failed for package 'plyr'
* removing '/usr/local/lib/R/site-library/plyr'

The downloaded source packages are in
        '/tmp/RtmpDBJ34O/downloaded_packages'
Warning message:
In install.packages("plyr", repos = "https://cran.rstudio.com/") :
  installation of package 'plyr' had non-zero exit status
> 
> 
```

**Comment by angelrr7702** [comment]
I check and I was able to install without problem within my container ... I google this error "g++: internal compiler error: Killed (program cc1plus)" and it appear to be relate to low memory ... recommendation to have swap space and 4g of ram for inside of container . ... check memory of your system and if possible you can stop temp some containers and after install have them back online or any other procedure that free some space for the installing compiling of this package..

**Comment by vikjam** [comment]
Hi, you were spot on! My googling had lead me to posts where people only recommended updating R. After adding more swap space, everything is working smoothly. Thanks for so much for your help!

```{bash}
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo /sbin/swapon /var/swap.1
sudo sh -c 'echo "/var/swap.1 swap swap defaults 0 0 " >> /etc/fstab'
```
